# SPDX-License-Identifier: GPL-2.0-only
obj-y				+= common.o biuctrl.o irqs.o
obj-$(CONFIG_BRCMSTB_PM)	+= pm/
obj-$(CONFIG_BRCMSTB_SRPD)	+= srpd.o
obj-$(CONFIG_GPIO_BRCMSTB)	+= gpio.o
obj-$(CONFIG_BRCMSTB_BMEM)	+= bmem.o
