# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_ARM)		+= s2-arm.o pm-arm.o
AFLAGS_s2-arm.o			:= -march=armv7-a
obj-$(CONFIG_ARM64)		+= s2-arm64.o pm-arm.o
AFLAGS_s2-arm64.o		:= -march=armv8-a
obj-$(CONFIG_BMIPS_GENERIC)	+= s2-mips.o s3-mips.o pm-mips.o
